apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  {{- if .spec.outputs }}
  outputs:
  - name: {{ (index .spec.outputs 0).name | toYaml }}
    type: kafka
    url: {{ (index .spec.outputs 0).kafka.url | toYaml }}
  {{- end }}
  {{- if .spec.pipelines }}
  pipelines:
    {{- .spec.pipelines | toYaml | nindent 2 }}
  {{- end }}

#apiVersion: "logging.openshift.io/v1"
#kind: ClusterLogForwarder
#metadata:
#  name: instance
#  namespace: openshift-logging
#spec:
#  outputs:
#    - type: "kafka"
#      name: kafka-open
#      url: tcp://10.46.55.190:9092/test
#  pipelines:
#  - inputRefs:
#    - audit
#    - infrastructure
#    labels:
#      label1: test1
#      label2: test2
#      label3: test3
#      label4: test4
#    name: all-to-default
#    outputRefs: 
#    - kafka-open  
