---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: test
  namespace: test
  annotations:
    ran.openshift.io/ztp-deploy-wave: "2"
spec:
  channel: "stable"
  name: test
  source: test
  sourceNamespace: test