name: '🔧 Gemini Create Fix'

on:
  issue_comment:
    types: [created]

concurrency:
  group: '${{ github.workflow }}-${{ github.event.issue.number }}'
  cancel-in-progress: false

defaults:
  run:
    shell: 'bash'

jobs:
  create-fix:
    runs-on: 'ubuntu-latest'
    if: |
      github.event.issue.state == 'open' &&
      contains(github.event.comment.body, '@gemini-cli create-fix')
    permissions:
      contents: 'write'
      id-token: 'write'
      issues: 'write'
      pull-requests: 'write'
    steps:
      - name: 'Mint identity token'
        id: 'mint_identity_token'
        if: |-
          ${{ vars.APP_ID }}
        uses: 'actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b' # ratchet:actions/create-github-app-token@v2
        with:
          app-id: '${{ vars.APP_ID }}'
          private-key: '${{ secrets.APP_PRIVATE_KEY }}'
          permission-contents: 'write'
          permission-issues: 'write'
          permission-pull-requests: 'write'

      - name: 'Run Gemini CLI - Create Fix'
        id: 'run_gemini_create_fix'
        uses: 'google-github-actions/run-gemini-cli@v0' # ratchet:exclude
        env:
          TITLE: '${{ github.event.issue.title }}'
          DESCRIPTION: '${{ github.event.issue.body }}'
          EVENT_NAME: '${{ github.event_name }}'
          GITHUB_TOKEN: '${{ steps.mint_identity_token.outputs.token || secrets.GITHUB_TOKEN || github.token }}'
          ISSUE_NUMBER: '${{ github.event.issue.number }}'
          REPOSITORY: '${{ github.repository }}'
        with:
          gemini_api_key: '${{ secrets.GEMINI_API_KEY }}'
          gcp_workload_identity_provider: '${{ vars.GCP_WIF_PROVIDER }}'
          gcp_project_id: '${{ vars.GOOGLE_CLOUD_PROJECT }}'
          gcp_location: '${{ vars.GOOGLE_CLOUD_LOCATION }}'
          gcp_service_account: '${{ vars.SERVICE_ACCOUNT_EMAIL }}'
          use_vertex_ai: '${{ vars.GOOGLE_GENAI_USE_VERTEXAI }}'
          google_api_key: '${{ secrets.GOOGLE_API_KEY }}'
          use_gemini_code_assist: '${{ vars.GOOGLE_GENAI_USE_GCA }}'
          gemini_debug: true
          gemini_model: '${{ vars.GEMINI_MODEL }}'
          settings: |-
            {
              "maxSessionTurns": 75,
              "telemetry": {
                "enabled": ${{ vars.GOOGLE_CLOUD_PROJECT != '' }},
                "target": "gcp"
              },
              "mcpServers": {
                "github": {
                  "command": "docker",
                  "args": [
                    "run",
                    "-i",
                    "--rm",
                    "-e",
                    "GITHUB_PERSONAL_ACCESS_TOKEN",
                    "ghcr.io/github/github-mcp-server"
                  ],
                  "includeTools": [
                    "add_issue_comment",
                    "get_issue",
                    "get_issue_comments",
                    "create_branch",
                    "create_or_update_file",
                    "get_file_contents",
                    "search_code",
                    "list_commits",
                    "get_commit"
                  ],
                  "env": {
                    "GITHUB_PERSONAL_ACCESS_TOKEN": "${GITHUB_TOKEN}"
                  }
                }
              },
              "coreTools": [
                "run_shell_command(find)",
                "run_shell_command(grep)",
                "run_shell_command(cat)",
                "run_shell_command(head)",
                "run_shell_command(tail)"
              ]
            }
          prompt: |-
            You are a security engineer implementing CVE fixes for repository ${{ env.REPOSITORY }}.

            Repository context:
            - Contains cnf-tests and ztp-site-generate containers
            - ztp-site-generate is the same as resource-generator (different names, same container)
            - The ztp-site-generate container is built from ztp/resource-generator/Containerfile (not Dockerfile!)
            - Look for Containerfile in ztp/resource-generator/ directory

            TASK: Create a fix branch for CVE issue #${{ env.ISSUE_NUMBER }}.

            STEP 1: Read the CVE analysis
            - Use mcp__github__get_issue_comments to read all comments on issue #${{ env.ISSUE_NUMBER }}
            - Find the CVE analysis comment with the proposed fix
            - Extract the specific fix recommendations

            STEP 2: Identify and examine files
            - Use mcp__github__search_code to find "Containerfile" in the repository
            - Use mcp__github__get_file_contents to read ztp/resource-generator/Containerfile
            - IMPORTANT: Only work with files in THIS repository, do not access external URLs or GitLab links

            STEP 3: Create fix branch and implement changes
            - Use mcp__github__create_branch to create branch "cve-fix" based on master
            - Use mcp__github__create_or_update_file to implement the recommended fixes
            - Use commit message: "fix: address ${{ env.TITLE }} security vulnerability"

            STEP 4: Report completion
            - Use mcp__github__add_issue_comment to post completion summary

            Execute these steps now.