name: '🔧 Gemini Create Fix (Minimal)'

on:
  issue_comment:
    types: [created]

concurrency:
  group: '${{ github.workflow }}-${{ github.event.issue.number }}'
  cancel-in-progress: false

defaults:
  run:
    shell: 'bash'

jobs:
  create-fix-minimal:
    runs-on: 'ubuntu-latest'
    if: |
      github.event.issue.state == 'open' &&
      contains(github.event.comment.body, '@gemini-cli create-fix-minimal')
    permissions:
      contents: 'write'
      id-token: 'write'
      issues: 'write'
      pull-requests: 'write'
    steps:
      - name: 'Mint identity token'
        id: 'mint_identity_token'
        if: |-
          ${{ vars.APP_ID }}
        uses: 'actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b' # ratchet:actions/create-github-app-token@v2
        with:
          app-id: '${{ vars.APP_ID }}'
          private-key: '${{ secrets.APP_PRIVATE_KEY }}'
          permission-contents: 'write'
          permission-issues: 'write'
          permission-pull-requests: 'write'

      - name: 'Run Gemini CLI - Minimal Fix'
        id: 'run_gemini_minimal_fix'
        timeout-minutes: 3
        uses: 'google-github-actions/run-gemini-cli@v0' # ratchet:exclude
        env:
          TITLE: '${{ github.event.issue.title }}'
          DESCRIPTION: '${{ github.event.issue.body }}'
          EVENT_NAME: '${{ github.event_name }}'
          GITHUB_TOKEN: '${{ steps.mint_identity_token.outputs.token || secrets.REPO_TOKEN || github.token }}'
          ISSUE_NUMBER: '${{ github.event.issue.number }}'
          REPOSITORY: '${{ github.repository }}'
        with:
          gemini_api_key: '${{ secrets.GEMINI_API_KEY }}'
          gcp_workload_identity_provider: '${{ vars.GCP_WIF_PROVIDER }}'
          gcp_project_id: '${{ vars.GOOGLE_CLOUD_PROJECT }}'
          gcp_location: '${{ vars.GOOGLE_CLOUD_LOCATION }}'
          gcp_service_account: '${{ vars.SERVICE_ACCOUNT_EMAIL }}'
          use_vertex_ai: '${{ vars.GOOGLE_GENAI_USE_VERTEXAI }}'
          google_api_key: '${{ secrets.GOOGLE_API_KEY }}'
          use_gemini_code_assist: '${{ vars.GOOGLE_GENAI_USE_GCA }}'
          gemini_debug: true
          gemini_model: '${{ vars.GEMINI_MODEL }}'
          settings: |-
            {
              "maxSessionTurns": 8,
              "telemetry": {
                "enabled": ${{ vars.GOOGLE_CLOUD_PROJECT != '' }},
                "target": "gcp"
              },
              "mcpServers": {
                "github": {
                  "command": "docker",
                  "args": [
                    "run",
                    "-i",
                    "--rm",
                    "-e",
                    "GITHUB_PERSONAL_ACCESS_TOKEN",
                    "ghcr.io/github/github-mcp-server"
                  ],
                  "includeTools": [
                    "create_branch",
                    "create_or_update_file",
                    "add_issue_comment"
                  ],
                  "env": {
                    "GITHUB_PERSONAL_ACCESS_TOKEN": "${GITHUB_TOKEN}"
                  }
                }
              }
            }
          prompt: |-
            You are implementing CVE-2025-7195 fix for repository ${{ env.REPOSITORY }}.

            TASK: Create branch "cve-fix-issue-${{ env.ISSUE_NUMBER }}" with security fix applied.

            EXECUTE EXACTLY THESE 3 STEPS:

            1. CREATE BRANCH using mcp__github__create_branch:
            - owner: "abraham2512"
            - repo: "cnf-features-deploy"
            - branch: "cve-fix-issue-${{ env.ISSUE_NUMBER }}"
            - from_branch: "master"

            2. APPLY FIX using mcp__github__create_or_update_file:
            - owner: "abraham2512"
            - repo: "cnf-features-deploy"
            - path: "ztp/resource-generator/Containerfile"
            - branch: "cve-fix-issue-${{ env.ISSUE_NUMBER }}"
            - message: "fix: add chmod 644 for /etc/passwd (CVE-2025-7195)"
            - content: Replace the current Containerfile content by adding "RUN chmod 644 /etc/passwd" on the line immediately before "USER 1001" (around line 67).

            3. REPORT SUCCESS using mcp__github__add_issue_comment:
            - owner: "abraham2512"
            - repo: "cnf-features-deploy"
            - issue_number: ${{ env.ISSUE_NUMBER }}
            - body: "✅ CVE fix completed!\n\nBranch created: cve-fix-issue-${{ env.ISSUE_NUMBER }}\nFix applied: Added RUN chmod 644 /etc/passwd\nReady for PR creation"

            Execute these 3 steps now. Do NOT read any files or comments.